apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: $serviceName
  labels:
    app: $serviceName
    tier: Service
  name: $serviceName
  namespace: services
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: $serviceName
  template:
    metadata:
      labels:
        app: $serviceName
      name: $serviceName
    spec:
      containers:
      - name: $serviceName
        image: lykkebusiness/service-$serviceName:dev
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            memory: 128Mi
            cpu: 40m
          limits:
            memory: 1024Mi
            cpu: 1000m
        env:
        - name: BuildNumber
          value: '$version'
        - name: SettingsUrl
          value: '$ConnectionString'
        - name: ENV_INFO
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MyMonitoringUrl
          value: http://$serviceName.services.svc.cluster.local/api/isalive
        - name: CPApiKey
          valueFrom:
            secretKeyRef:
              name: $serviceName
              key: CPApiKey
