apiVersion: v1
kind: Service
metadata:
  labels:
    app: $serviceName
    environment: Live
  name: $serviceName
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: $serviceName
  sessionAffinity: None
  type: ClusterIP
